export const moviesListMock = [
  {
    adult: false,
    backdrop_path: '/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg',
    genre_ids: [28, 12, 878],
    id: 640146,
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    popularity: 8567.865,
    poster_path: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
    release_date: '2023-02-15',
    title: 'Ant-Man and the Wasp: Quantumania',
    video: false,
    vote_average: 6.5,
    vote_count: 1886,
  },
  {
    adult: false,
    backdrop_path: '/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg',
    genre_ids: [16, 12, 10751, 14, 35],
    id: 502356,
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview:
      'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    popularity: 6572.614,
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    release_date: '2023-04-05',
    title: 'The Super Mario Bros. Movie',
    video: false,
    vote_average: 7.5,
    vote_count: 1456,
  },
  {
    adult: false,
    backdrop_path: '/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg',
    genre_ids: [28, 35, 14],
    id: 594767,
    original_language: 'en',
    original_title: 'Shazam! Fury of the Gods',
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    popularity: 4274.232,
    poster_path: '/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg',
    release_date: '2023-03-15',
    title: 'Shazam! Fury of the Gods',
    video: false,
    vote_average: 6.9,
    vote_count: 1231,
  },
  {
    adult: false,
    backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    popularity: 3365.913,
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Way of Water',
    video: false,
    vote_average: 7.7,
    vote_count: 7535,
  },
  {
    adult: false,
    backdrop_path: '/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg',
    genre_ids: [28, 12, 36, 18, 10752],
    id: 948713,
    original_language: 'en',
    original_title: 'The Last Kingdom: Seven Kings Must Die',
    overview:
      "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
    popularity: 3119.049,
    poster_path: '/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg',
    release_date: '2023-04-14',
    title: 'The Last Kingdom: Seven Kings Must Die',
    video: false,
    vote_average: 7.4,
    vote_count: 232,
  },
];
